{"uuid":"46d7532e-b705-40a0-aefe-3dbfbae0456d","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["43bdd8d5-7763-4ed8-821c-6d7f3586691c"],"befores":[],"afters":[{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687881656068,"stop":1687881656068},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687881656258,"stop":1687881656258},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687881656311,"stop":1687881656311},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687881656349,"stop":1687881656349},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687881656354,"stop":1687881656354}],"start":1687881655976,"stop":1687881656354}